patch: improve azure cloud deployment to match the mongodb sharded cluster deployment (#24)
## Description

This PR fixes a couple of issues that I had when deploying a
charmed-mongodb sharded cluster in azure

- The juju controller machine was too small so when launching the deploy
of a sharded cluster (many units) the machine just died -> we now set
constraints to the juju controller machine
- The `Standard_D4s_v3` machines used in the AKS nodes did not allow
enough storage attachements -> we can choose the number of nodes and the
machine flavor. see
https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dv3-series?tabs=sizestorageremote
- Improve readme
- Fix the security groups deployment
```
Error: Invalid function argument
│ 
│   on security_groups.tf line 58, in resource "azurerm_network_security_group" "main_nsg":
│   58:     source_address_prefixes    = var.SOURCE_ADDRESSES == null ? ["0.0.0.0/0"] : concat(var.SOURCE_ADDRESSES, azurerm_virtual_network.main_vnet.address_space)
│     ├────────────────
│     │ while calling concat(seqs...)
│     │ azurerm_virtual_network.main_vnet.address_space is set of string with 1 element
│ 
│ Invalid value for "seqs" parameter: all arguments must be lists or tuples; got set of string.
```